apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: frontend-service
    path: patch.yaml

images:
  - name: weeturtle/frontend
    newTag: e22be16
