apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: chores-service
    path: patch.yaml

images:
  - name: weeturtle/chores
    newTag: 105ef009e780cb1db29e82701ff95dd6457326f0
