apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: nginx-ingress-controller
    path: patch.yaml
