apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: kubernetes.cs.bath.ac.uk
      http:
        paths:
          - path: /chores(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chores-service
                port:
                  number: 3000
          - path: /users(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 3000
